### ISSUE TITLE
Remove 3xx redirect on API project

### ISSUE THREAD

**Issue by openmosix** [Gild/gild-api#1]
Following on https://github.com/Gild/gild-api#require-secure-connections we should remove the 3xx redirect from the API project.

**Comment by openmosix** [comment]
cc: @taganaka @stefanofontanelli @andreacfm

**Comment by openmosix** [comment]
Ok, I got a :+1: from everyone, so I guess we will get this going. cc: @gbagnoli

**Comment by gbagnoli** [comment]
I can't remove the port from the ELB as it's shared between all apps. I'll edit the nginx conf instead, and fix this tomorrow.

**Comment by openmosix** [comment]
That was fast :dancers: Thanks!

**Comment by gbagnoli** [comment]
Implemented here: https://github.com/Gild/ops/commit/3119f46efcd091625c352eb48df19cc24242ee00

Deployed on staging, will activate the change on production if nothing breaks.

**Comment by openmosix** [comment]
Thanks!

**Comment by gbagnoli** [comment]
btw this has been moved in prod and the NR ping broke. Going to fix that.

**Comment by gbagnoli** [comment]
probe restored.

**Comment by openmosix** [comment]
:+1:
