### ISSUE TITLE
Rate limit status

### ISSUE THREAD

**Issue by openmosix** [Gild/gild-api#11]
@taganaka you worked on this. Are the standards X-Rate-Limits present in the HTTP response?

https://github.com/Gild/gild-api#rate-limit-status

**Comment by taganaka** [comment]
nope. No headers about current limits are exposed yet. 
The only thing handled now is the 429 HTTP code back off message

**Comment by openmosix** [comment]
Shall we add it? (in our todo)

**Comment by taganaka** [comment]
yep :+1:
