### ISSUE TITLE
Use only utc and iso format

### ISSUE THREAD

**Issue by andreacfm** [Gild/gild-api#13]
Any thoughts on this?

https://github.com/Gild/gild-api#utc-times-formatted-in-iso8601

**Comment by andreacfm** [comment]
:+1:

**Comment by taganaka** [comment]
Agreed on this

**Comment by openmosix** [comment]
:+1:

**Comment by andreacfm** [comment]
Started here https://github.com/Gild/tuna-api/pull/1045

**Comment by openmosix** [comment]
@andreacfm @taganaka I'm closing this (as issue). I think we are all on the same page about this, we should start adding this as standard component for all the req/response of V2.
