### ISSUE TITLE
File format for download / upload

### ISSUE THREAD

**Issue by openmosix** [Gild/gild-api#14]
We need to standardize the way we will handle binary files in upload and download. The bottom line being: the binary data can't be part of the regular JSON structure.

We have established the rule that all the POST and PUT/PATCH must have a json-encoded payload. However to upload a file we need to switch to multipart/form-encoded to send a binary part.

Things like this one

https://github.com/Gild/tuna-api/blob/master/app/api/platform_api/v1/api_companies.rb#L75

are "forbidden", because the "logo" is not an actual parameter, is a multipart of the request. This means the client needs to handle it differently than a regular POST/PUT/PATCH. Moreover sending a mixed format (half json and half file) can be very very messy.

Same as

https://github.com/Gild/tuna-api/blob/master/app/api/platform_api/v1/api_profiles.rb#L47

will not be supported. It's worth noting we had to manually patch the tuna-rest-client (see https://github.com/Gild/tuna-rest-client/blob/master/lib/tuna-rest-client/services/profile.rb#L25) because standard REST clients have no clue how to support a mixed json/multipart.

I'm hitting this in the swagger generator - the way we are currently handling files in the API is non standard. In our API we are currently mixing all the styles, so we should decide for one.

Options:

1. We go for a standard json-encoding (both in the response of methods and upload methods, like PUT/PATCH) but "files" are base64 encoded. An example: https://github.com/Gild/tuna-api/blob/master/app/api/entities/company_entity.rb#L14  Here the logo is defined within an entity as a "string". We can then support entities in upload and download as base64, the entity can take care of the base64 decode/encode. The documentation has to point out it's a base64 encoded field. Pro: easy. Cons: messy if it's a big file, can crash for larger upload/download

2. A dedicated endpoint to upload files, using binary transfer as part of a url-form-encoded request. See https://github.com/Gild/tuna-api/blob/master/app/api/platform_api/v1/api_messages.rb#L150  In this case the endpoint is a url form encoded request and one of the parameter is a "file".

3.  A dedicated endpoint to upload files, using a link upload. This works in conjunction with services like filepicker. The file is actually uploaded to a 3rd-party service (file-picker). The API only support a url to the stored file (in upload). See https://github.com/Gild/tuna-api/blob/master/app/api/platform_api/v1/interviews/api_interviews.rb#L279

4. For download, we have a url pointing to the actual content of the file. We never transfer data from the API (no download). The client will receive the url and download the content from the url.

@stefanoc @andreacfm @taganaka @tejo thoughts?

I'd go for 4 for downloads, 2 or 3 for uploads.

**Comment by taganaka** [comment]
Definitely I'd avoid number 1.

:1 for number 4

Still uncertain between 2 and 3

**Comment by andreacfm** [comment]
Number 4 is a winner.
On point 2/3 I am thinking about permissions. Will be reasonable having more endpoints to upload files related to different resources?
The permissions to upload a company logo could be different from the permissions required to upload something related to a different resource.
Make sense?

**Comment by tejo** [comment]
I think number 4 is a no-brainer. 

For uploading I'm ok for having a dedicated endpoint for resource, eg:

```
/profile
/profile/uploads
/job_post/
/job_post/uploads
```

we should write an endpoint (or action) that can be mounted (or aliased) and nested inside a resource. 
so we can configure the permissions related to the resource.

Using an external API or not it's not a big difference for me. 
Probably file picker is ok, it just works.

**Comment by stefanoc** [comment]
I vote for number 3. Sidestepping all the hassles related to file uploads will save us a lot of headaches.
It also allows us to make some endpoints asynchronous if needed.

**Comment by openmosix** [comment]
One thing about #3 is filepicker must be accessed client side (i.e the client uploads the file on the 3rd party service, get a url, send an API call to us with the url). In this case we need to figure out how a client can access the 3rd party service - i.e. if Facebook wants to upload resumes on our API, do we need to handover the private key of file picker?

**Comment by tejo** [comment]
@openmosix yes you are very right about number 3. Maybe we can implement a proxy to the filepicker service...

**Comment by openmosix** [comment]
Oki doki. I'll be create the proxy service (media) for the API. The documentation is already in. https://github.com/Gild/api/tree/handle-media-uploads

Closing this.
