### ISSUE TITLE
Add/test ETag support in the API

### ISSUE THREAD

**Issue by openmosix** [Gild/gild-api#2]
Following on 

https://github.com/Gild/gild-api/#support-etags-for-caching

we should check if the current setup already supports etag/caching (https://github.com/snowyu/rest_service/wiki/ETags-in-Grape)

**Comment by openmosix** [comment]
cc: @andreacfm @taganaka

**Comment by taganaka** [comment]
There is some work to do here.
While it's easy to determine whether a single object has been modified eg by looking at its `chache_key` it is not when you have to deal with complex structures or a list of items where the checksum needs to be computed on the entire result set

I think we need to experiment a little bit around this topic before to kick in etag support everywhere.

**Comment by andreacfm** [comment]
Agree. This  is not easy to implement and maintain in a correct way.

Il mercoledì 24 giugno 2015, Francesco Laurita <notifications@github.com>
ha scritto:

> There is some work to do here.
> While it's easy to determine whether a single object has been modified eg
> by looking at its chache_key it is not when you have to deal with complex
> structures or a list of items where the checksum needs to be computed on
> the entire result set
>
> I think we need to experiment a little bit around this topic before to
> kick in etag support everywhere.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gild/gild-api/issues/2#issuecomment-114975263>.
>


-- 
Inviato da Gmail Mobile

**Comment by openmosix** [comment]
Do we want to remove it? I.e. no ETag support?

**Comment by taganaka** [comment]
I would remove it

On Wed, Jun 24, 2015 at 1:59 PM, Luca Bonmassar <notifications@github.com>
wrote:

> Do we want to remove it? I.e. no ETag support?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gild/gild-api/issues/2#issuecomment-115010735>.
>



-- 
Francesco Laurita
Vice President of Engineering | Gild, Inc.
800-664-2366  | cell 415 694 9038

465 California Street, Suite 1200
San Francisco, CA 94104
www.gild.com

**Comment by andreacfm** [comment]
:+1: to remove it

**Comment by openmosix** [comment]
Done. https://github.com/Gild/gild-api/pull/9
