### ISSUE TITLE
Provide request IDs for introspection

### ISSUE THREAD

**Issue by openmosix** [Gild/gild-api#3]
As mentioned in https://github.com/Gild/gild-api#provide-request-ids-for-introspection
we should move the RequestUUID we are currently generating on the server side and embeds it in the X- headers in the response.

**Comment by andreacfm** [comment]
I like this but probably we should think about a general idea of what can be a plan to store the requestUUID for future introspection.
Managing the RequestUUID itself doesn't looks like a great effort but making this available for debugging can be a challenge.

**Comment by openmosix** [comment]
I think for us it would be very valuable (with access to logs and you can inspect the X-Request-ID in the chrome dev tool). For who has no access to logs, what about the api log auditing?

**Comment by taganaka** [comment]
we can extend the logging mechanism for api request auditing to store X-Request-ID as well so that we can easily filter and aggregate by the value

**Comment by andreacfm** [comment]
@openmosix @taganaka 
Using the auditing log makes sense. Thanks

**Comment by openmosix** [comment]
Ok, I'm marking this as "decided"

**Comment by andreacfm** [comment]
:+1:

**Comment by openmosix** [comment]
This is currently implemented:

ᐅ curl -is http://localhost:4100/v1/me                       
HTTP/1.1 401 Unauthorized
Content-Type: application/json
**X-Request-Id: 7380cb11-4b2e-4788-b69d-8a6763f4df31**
X-Runtime: 2.352474
Content-Length: 59

{"message":"Not Authenticated","error":"not_authenticated"}


I, [2015-06-28T11:38:47.180430 #26685]  INFO -- : **[7380cb11-4b2e-4788-b69d-8a6763f4df31]** 401/59 GET "/v1/me" for "127.0.0.1" at 2015-06-28T11:38:47-07:00 in 2349.8 ms
D, [2015-06-28T11:38:47.180536 #26685] DEBUG -- : **[7380cb11-4b2e-4788-b69d-8a6763f4df31]** Path "/v1/me", query "", params ""
D, [2015-06-28T11:38:47.180638 #26685] DEBUG -- : **[7380cb11-4b2e-4788-b69d-8a6763f4df31]** Resp Headers: {"Content-Type"=>"application/json", "Content-Length"=>"59"}
D, [2015-06-28T11:38:47.181052 #26685] DEBUG -- : **[7380cb11-4b2e-4788-b69d-8a6763f4df31]** Resp Body: {"message"=>"Not Authenticated", "error"=>"not_authenticated"}
D, [2015-06-28T11:38:47.181197 #26685] DEBUG -- : **[7380cb11-4b2e-4788-b69d-8a6763f4df31]** ---
