### ISSUE TITLE
Sending parameters as JSON in content

### ISSUE THREAD

**Issue by openmosix** [Gild/gild-api#6]
We currently support this:

https://github.com/Gild/gild-api#accept-serialized-json-in-request-bodies

What's your thoughts about:

* Supporting JSON AND url-form-encoded? Several REST client implementations trip on complex url-form-encoded parameters. In the tuna-rest-client we are switching by default on json-encoded. I think it would decrease the chance of implementation problems client-side
* How do we feel about the implementation of GET and DELETE? We have said no parameters in the query part - we can either encode all in the path (terrible) or change the rule of params in the path for these verbs.

cc: @andreacfm @taganaka @tejo

**Comment by openmosix** [comment]
cc: @stefanoc @liquid1982

**Comment by liquid1982** [comment]
I would support both JSON and url form encoded. About the second point, I would not allow sending a json encoded string as a query parameter.

**Comment by stefanoc** [comment]
I would adopt a simple rule:
* POST/PUT/PATCH: serialized JSON in the request body
* GET: url-encoded parameters in the query string
* DELETE: none of the above

**Comment by openmosix** [comment]
@stefanoc yes, I'd go for a rule. Having a pre-defined rule will allow us to make the documentation by convention, so I can code it in our swagger parser and autogenerate the clients following that rule.
I'll go for the convention you have mentioned (DELETE should probably have url-encoded parameters in case it has filters).
